providers = ["python"]

# Optional but recommended to pin a version. Use either this variable
# or a .tool-versions file; either works.
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
# System packages for MoviePy/text rendering
nixPkgs = ["ffmpeg", "imagemagick", "fontconfig", "dejavu_fonts"]

# Override install so it doesn't call `python` (which is missing)
[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

# You can remove the previous build-phase symlink; it’s no longer needed.
