[phases.setup]
nixPkgs = ["ffmpeg", "imagemagick", "fontconfig", "dejavu_fonts"]

providers = ["python"]

[providers.python]
version = "3.11"

[phases.setup]
# System packages MoviePy/text rendering needs
nixPkgs = ["ffmpeg", "imagemagick", "fontconfig", "dejavu_fonts"]

# Safety: ensure `python` alias exists if the builder calls `python` instead of `python3`
[phases.build]
cmds = [
  "ln -sf $(command -v python3) /usr/local/bin/python || true"
]
