providers = ["python"]

[providers.python]
version = "3.11"

[phases.setup]
nixPkgs = ["ffmpeg", "imagemagick", "fontconfig", "dejavu_fonts"]

[phases.build]
cmds = [
  "ln -sf $(command -v python3) /usr/local/bin/python || true"
]
