providers = ["python"]

[variables]
# Optional: pin the Python version Nixpacks/provider prefers to use.
# You can keep this or remove it; Python will come from nixPkgs either way.
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
# Add python311 so python3 exists; keep your media packages.
nixPkgs = ["python311", "ffmpeg", "imagemagick", "fontconfig", "dejavu_fonts"]
# Make sure `python` is available in case something calls it
cmds = [
  "ln -sf $(command -v python3) /usr/local/bin/python || true"
]

# Keep your start command in Railway UI or define it here if you prefer:
# [start]
# cmd = "gunicorn -b 0.0.0.0:$PORT --timeout 600 app:app"
